// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQE8FyoAI681FQZvWJPIdPMLeK1jifwI',
    appId: '1:304660168017:web:b129bd955eb9e09318a770',
    messagingSenderId: '304660168017',
    projectId: 'fin-app-26-v0',
    authDomain: 'fin-app-26-v0.firebaseapp.com',
    storageBucket: 'fin-app-26-v0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYl1ECUPeKxE7Q24-3XVdQH3p4QCC0gc',
    appId: '1:304660168017:android:a918d86c38b9e97618a770',
    messagingSenderId: '304660168017',
    projectId: 'fin-app-26-v0',
    storageBucket: 'fin-app-26-v0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZH53E-BndiLJvhyUHWe9HpJo8Dtz0SU',
    appId: '1:304660168017:ios:a1e1976bb9124c4918a770',
    messagingSenderId: '304660168017',
    projectId: 'fin-app-26-v0',
    storageBucket: 'fin-app-26-v0.firebasestorage.app',
    iosBundleId: 'com.arthurasasira.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZH53E-BndiLJvhyUHWe9HpJo8Dtz0SU',
    appId: '1:304660168017:ios:a1e1976bb9124c4918a770',
    messagingSenderId: '304660168017',
    projectId: 'fin-app-26-v0',
    storageBucket: 'fin-app-26-v0.firebasestorage.app',
    iosBundleId: 'com.arthurasasira.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQE8FyoAI681FQZvWJPIdPMLeK1jifwI',
    appId: '1:304660168017:web:309b0ac2ef4afe8718a770',
    messagingSenderId: '304660168017',
    projectId: 'fin-app-26-v0',
    authDomain: 'fin-app-26-v0.firebaseapp.com',
    storageBucket: 'fin-app-26-v0.firebasestorage.app',
  );
}
