// Generated by flutterfire configure — run that command to replace this stub.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Run `flutterfire configure` to generate firebase_options.dart '
      'before building or running the app.',
    );
  }
}
