# Generated by Django 5.2.16 on 2026-07-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('recurring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='occurrence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='recurring.occurrence'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeevent',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='income_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.incomeevent'),
        ),
        migrations.AddConstraint(
            model_name='bucket',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'name'), name='unique_active_bucket_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'occurred_on'], name='ledger_expe_user_id_b78d68_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeevent',
            index=models.Index(fields=['user', 'occurred_on'], name='ledger_inco_user_id_3d7c16_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeevent',
            index=models.Index(fields=['user', 'source'], name='ledger_inco_user_id_e54f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['user', 'bucket'], name='ledger_allo_user_id_a0b8e7_idx'),
        ),
    ]
