# Generated by Django 5.2.16 on 2026-07-16 13:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='incomeevent',
            name='gross_minor',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='incomeevent',
            name='kind',
            field=models.CharField(choices=[('paycheque', 'Paycheque'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='incomeevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gross_minor__isnull', True), ('kind', 'other')), models.Q(('gross_minor__isnull', False), ('kind', 'paycheque')), _connector='OR'), name='gross_iff_paycheque'),
        ),
        migrations.AddConstraint(
            model_name='incomeevent',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor__isnull', True), ('gross_minor__gte', models.F('amount_minor')), _connector='OR'), name='gross_gte_takehome'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='income_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='ledger.incomeevent'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
