# Generated by Django 5.2.16 on 2026-07-16 13:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=10)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_on', models.DateField()),
                ('end_on', models.DateField(blank=True, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='ledger.bucket')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RatePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_from', models.DateField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurring_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_periods', to='recurring.recurringpayment')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_on', models.DateField()),
                ('expected_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('skipped', 'Skipped'), ('linked', 'Linked')], default='pending', max_length=10)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurring_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='recurring.recurringpayment')),
            ],
            options={
                'ordering': ['due_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(condition=models.Q(('end_on__isnull', True), ('end_on__gte', models.F('start_on')), _connector='OR'), name='recurring_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frequency', 'custom'), _negated=True), ('interval_days__isnull', False), _connector='OR'), name='recurring_custom_requires_interval'),
        ),
        migrations.AddConstraint(
            model_name='rateperiod',
            constraint=models.UniqueConstraint(fields=('recurring_payment', 'effective_from'), name='unique_rate_period_start'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['user', 'status', 'due_on'], name='recurring_o_user_id_243ad0_idx'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(fields=('recurring_payment', 'due_on'), name='unique_occurrence_per_due_date'),
        ),
    ]
